/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ICE64RendererInterface extends utils.Interface {
  functions: {
    "dataStore()": FunctionFragment;
    "drawSVGToBytes(bytes)": FunctionFragment;
    "drawSVGToString(bytes)": FunctionFragment;
    "getEditionPhotoBase64SVG(uint256)": FunctionFragment;
    "getEditionPhotoSVG(uint256)": FunctionFragment;
    "ice64()": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "xqstgfx()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "dataStore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drawSVGToBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawSVGToString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEditionPhotoBase64SVG",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEditionPhotoSVG",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ice64", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "xqstgfx", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dataStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawSVGToBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawSVGToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEditionPhotoBase64SVG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEditionPhotoSVG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ice64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xqstgfx", data: BytesLike): Result;

  events: {};
}

export interface ICE64Renderer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICE64RendererInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dataStore(overrides?: CallOverrides): Promise<[string]>;

    drawSVGToBytes(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    drawSVGToString(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEditionPhotoBase64SVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEditionPhotoSVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ice64(overrides?: CallOverrides): Promise<[string]>;

    tokenURI(id: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    xqstgfx(overrides?: CallOverrides): Promise<[string]>;
  };

  dataStore(overrides?: CallOverrides): Promise<string>;

  drawSVGToBytes(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  drawSVGToString(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  getEditionPhotoBase64SVG(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getEditionPhotoSVG(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  ice64(overrides?: CallOverrides): Promise<string>;

  tokenURI(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  xqstgfx(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    dataStore(overrides?: CallOverrides): Promise<string>;

    drawSVGToBytes(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    drawSVGToString(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getEditionPhotoBase64SVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getEditionPhotoSVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    ice64(overrides?: CallOverrides): Promise<string>;

    tokenURI(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

    xqstgfx(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    dataStore(overrides?: CallOverrides): Promise<BigNumber>;

    drawSVGToBytes(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    drawSVGToString(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEditionPhotoBase64SVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEditionPhotoSVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ice64(overrides?: CallOverrides): Promise<BigNumber>;

    tokenURI(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    xqstgfx(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    dataStore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    drawSVGToBytes(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drawSVGToString(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEditionPhotoBase64SVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEditionPhotoSVG(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ice64(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenURI(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    xqstgfx(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
