/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IGraphicsInterface extends utils.Interface {
  functions: {
    "draw(bytes)": FunctionFragment;
    "drawRects(bytes)": FunctionFragment;
    "drawRectsUnsafe(bytes)": FunctionFragment;
    "drawUnsafe(bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "draw", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "drawRects",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawRectsUnsafe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawUnsafe",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "draw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drawRects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawRectsUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawUnsafe", data: BytesLike): Result;

  events: {};
}

export interface IGraphics extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGraphicsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    draw(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    drawRects(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    drawRectsUnsafe(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    drawUnsafe(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;
  };

  draw(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  drawRects(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  drawRectsUnsafe(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  drawUnsafe(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    draw(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    drawRects(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    drawRectsUnsafe(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    drawUnsafe(data: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    draw(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    drawRects(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    drawRectsUnsafe(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    drawUnsafe(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    draw(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drawRects(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drawRectsUnsafe(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drawUnsafe(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
