/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IICE64DataStoreInterface extends utils.Interface {
  functions: {
    "getBaseURI()": FunctionFragment;
    "getRawPhotoData(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBaseURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRawPhotoData",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRawPhotoData",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IICE64DataStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IICE64DataStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getBaseURI(overrides?: CallOverrides): Promise<[string]>;

    getRawPhotoData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getBaseURI(overrides?: CallOverrides): Promise<string>;

  getRawPhotoData(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getBaseURI(overrides?: CallOverrides): Promise<string>;

    getRawPhotoData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getBaseURI(overrides?: CallOverrides): Promise<BigNumber>;

    getRawPhotoData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBaseURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRawPhotoData(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
