/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IICE64Interface extends utils.Interface {
  functions: {
    "getEditionTokenId(uint256)": FunctionFragment;
    "getMaxEditions()": FunctionFragment;
    "getOriginalTokenId(uint256)": FunctionFragment;
    "isEdition(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEditionTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxEditions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOriginalTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEdition",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEditionTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxEditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOriginalTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEdition", data: BytesLike): Result;

  events: {};
}

export interface IICE64 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IICE64Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getEditionTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaxEditions(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOriginalTokenId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isEdition(id: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;
  };

  getEditionTokenId(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMaxEditions(overrides?: CallOverrides): Promise<BigNumber>;

  getOriginalTokenId(
    editionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isEdition(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getEditionTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxEditions(overrides?: CallOverrides): Promise<BigNumber>;

    getOriginalTokenId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isEdition(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getEditionTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxEditions(overrides?: CallOverrides): Promise<BigNumber>;

    getOriginalTokenId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isEdition(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getEditionTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxEditions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOriginalTokenId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isEdition(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
