/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IThankYouInterface extends utils.Interface {
  functions: {
    "ty()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ty", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ty", data: BytesLike): Result;

  events: {
    "ThankYouMessage(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ThankYouMessage"): EventFragment;
}

export type ThankYouMessageEvent = TypedEvent<
  [string, string],
  { sender: string; message: string }
>;

export type ThankYouMessageEventFilter = TypedEventFilter<ThankYouMessageEvent>;

export interface IThankYou extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IThankYouInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "ty()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "ty(string)"(
      message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "ty()"(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "ty(string)"(
    message: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "ty()"(overrides?: CallOverrides): Promise<void>;

    "ty(string)"(message: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ThankYouMessage(address,string)"(
      sender?: null,
      message?: null
    ): ThankYouMessageEventFilter;
    ThankYouMessage(sender?: null, message?: null): ThankYouMessageEventFilter;
  };

  estimateGas: {
    "ty()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "ty(string)"(
      message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "ty()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "ty(string)"(
      message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
