/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface XQSTValidateInterface extends utils.Interface {
  functions: {
    "MAX_COLORS()": FunctionFragment;
    "MAX_COLS()": FunctionFragment;
    "MAX_PIXELS()": FunctionFragment;
    "MAX_ROWS()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_COLORS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_COLS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_PIXELS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_ROWS", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MAX_COLORS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_COLS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_PIXELS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_ROWS", data: BytesLike): Result;

  events: {};
}

export interface XQSTValidate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: XQSTValidateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_COLORS(overrides?: CallOverrides): Promise<[number]>;

    MAX_COLS(overrides?: CallOverrides): Promise<[number]>;

    MAX_PIXELS(overrides?: CallOverrides): Promise<[number]>;

    MAX_ROWS(overrides?: CallOverrides): Promise<[number]>;
  };

  MAX_COLORS(overrides?: CallOverrides): Promise<number>;

  MAX_COLS(overrides?: CallOverrides): Promise<number>;

  MAX_PIXELS(overrides?: CallOverrides): Promise<number>;

  MAX_ROWS(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    MAX_COLORS(overrides?: CallOverrides): Promise<number>;

    MAX_COLS(overrides?: CallOverrides): Promise<number>;

    MAX_PIXELS(overrides?: CallOverrides): Promise<number>;

    MAX_ROWS(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    MAX_COLORS(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_COLS(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_PIXELS(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ROWS(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_COLORS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_COLS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_PIXELS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_ROWS(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
