/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGraphics, IGraphicsInterface } from "../IGraphics";

const _abi = [
  {
    inputs: [],
    name: "BackgroundColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColors",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColumns",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxPixels",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxRows",
    type: "error",
  },
  {
    inputs: [],
    name: "MissingHeader",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughData",
    type: "error",
  },
  {
    inputs: [],
    name: "PixelColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "draw",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawRects",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawRectsUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "drawUnsafe",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IGraphics__factory {
  static readonly abi = _abi;
  static createInterface(): IGraphicsInterface {
    return new utils.Interface(_abi) as IGraphicsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGraphics {
    return new Contract(address, _abi, signerOrProvider) as IGraphics;
  }
}
