/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IICE64DataStore,
  IICE64DataStoreInterface,
} from "../IICE64DataStore";

const _abi = [
  {
    inputs: [],
    name: "getBaseURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getRawPhotoData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IICE64DataStore__factory {
  static readonly abi = _abi;
  static createInterface(): IICE64DataStoreInterface {
    return new utils.Interface(_abi) as IICE64DataStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IICE64DataStore {
    return new Contract(address, _abi, signerOrProvider) as IICE64DataStore;
  }
}
