/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IThankYou, IThankYouInterface } from "../IThankYou";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ThankYouMessage",
    type: "event",
  },
  {
    inputs: [],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class IThankYou__factory {
  static readonly abi = _abi;
  static createInterface(): IThankYouInterface {
    return new utils.Interface(_abi) as IThankYouInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IThankYou {
    return new Contract(address, _abi, signerOrProvider) as IThankYou;
  }
}
